import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Overview',
      link: { type: 'generated-index', title: 'Overview' },
      items: [{ type: 'autogenerated', dirName: '00-overview' }],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Policies',
      link: { type: 'generated-index', title: 'Policies' },
      items: [{ type: 'autogenerated', dirName: '10-policies' }],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Standards',
      link: { type: 'generated-index', title: 'Standards' },
      items: [{ type: 'autogenerated', dirName: '20-standards' }],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Procedures (SOPs)',
      link: { type: 'generated-index', title: 'Procedures (SOPs)' },
      items: [{ type: 'autogenerated', dirName: '30-procedures' }],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Evidence',
      link: { type: 'generated-index', title: 'Evidence' },
      items: [{ type: 'autogenerated', dirName: '50-evidence' }],
      collapsed: true,
    },
  ],
};

export default sidebars;